name: Release
on:
  push:
    tags:
      - "v*"
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install make
      run: sudo apt install make
    - name: Install deps
      run: sudo apt install libgit2-dev libncurses-dev
    - name: Build
      run: make deb
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} package
        path: "*.deb"
  publish:
    needs: build
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: packages
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          packages/*/*.deb
