name: Release
on: [push]
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install make
      run: sudo apt install make
    - name: Build
      run: make deb
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} package
        path: "*.deb"
