name: Release
on:
  push:
    tags:
      - "v*"
  
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu:22.04", "centos:centos7"]
        include:
          - os: ubuntu:22.04
            install: apt update && apt install -y gcc make libgit2-dev libncurses-dev dpkg-dev
            target: deb
          - os: centos:centos7
            install: yum install -y make gcc rpmdevtools rpmlint libgit2-devel ncurses-devel ncurses-libs
            target: rpm
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install deps
      run: ${{ matrix.install }}
    - name: Build
      run: make ${{ matrix.target }}
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: built package
        path: "build/*"
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: packages
    - name: Upload packages
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        file: packages/*/*
        file_glob: true
